### ISSUE TITLE
Add minified css file?

### ISSUE THREAD

**Issue by cktang88** [robsheldon/sscaffold-css#1]
Could you add a minified version?

**Comment by devin-fee-ah** [comment]
Hmm, I’m not sure what the precedent is with CSS only repos, but I feel like compiled CSS is an artifact and should be a part of the release. I.e. https://help.github.com/en/github/administering-a-repository/creating-releases

**Comment by dfee** [comment]
I feel like this should be a part of the release: https://help.github.com/en/github/administering-a-repository/creating-releases

**Comment by robsheldon** [comment]
@dfee it's currently pre-release. I'll be following those guidelines once it hits 0.1.0. I just needed other folks to eyeball everything and let me know if I got anything super obviously wrong (like the default text color and font).

@cktang88 yep, it's on the todo list for 0.1.0.

**Comment by robsheldon** [comment]
First official release is out, 0.1.0, and includes a minified version.
