### ISSUE TITLE
Text size in uncomfortably large by-default

### ISSUE THREAD

**Issue by Avamander** [robsheldon/sscaffold-css#2]
When I visit the [demo page](https://sscaffold-css.com/) I had to turn zoom down to 67% because the font size and column length was simply too large, both for myself and when just comparing to other sites. I'm using a 19" 5:4 1280x1024 monitor and I suspect that might be one of the causes. 

This problem however does not exist with sites I've seen that use just Skeleton. Also mentioning just in case that Medium suffers from the same issue.

**Comment by robsheldon** [comment]
I've been playing around with this for a few days. It's a bit puzzling. I think you're right on the money with thinking it's your display settings. I duplicated your settings on my display, and although the text is a bit large, I'm not sure I'm seeing the same thing you are. Can you post a screenshot or something?

I can't identify anything in skeleton.css that would make a big difference here. The base font size on the `html` element is the same and there aren't any media queries that change it. It could be that I started with a slightly larger overall font size for readability at higher dpis and it just gets too big at lower dpis.

I've been experimenting with proportional font scaling and media queries for dpi. I'm going to try to combine those to gracefully adjust font sizing for different display geometries, but a screenshot from you would help me figure out how to tweak the scaling factors.

**Comment by Avamander** [comment]
![image](https://user-images.githubusercontent.com/5392141/72120464-b4b72580-3360-11ea-8bf5-0819809fb11f.png)

![image](https://user-images.githubusercontent.com/5392141/72120471-bc76ca00-3360-11ea-9f01-8a401c189f9a.png)

Skeleton.css's font size is practically the last font size that is reasonable on my screen, though even reducing to 90% would be my personal preference, scaffold.css on the other hand is just a bit too large by default.

**Comment by robsheldon** [comment]
Okay, cool. That pretty well matches what I was seeing then. I should have a fix out soon.

**Comment by robsheldon** [comment]
Can you visit https://newventuresoftware.com/blog/pixel-density-and-resolution-tool-for-css-media-queries.html (click through the expired certificate, I guess...) and tell me what your dpi &etc. values are?

**Comment by Avamander** [comment]
![image](https://user-images.githubusercontent.com/5392141/72196090-94e63700-341e-11ea-985c-fafe542eaae4.png)

**Comment by robsheldon** [comment]
Not the numbers I was hoping for.

Okay, how does https://sscaffold-css.com/test/homepage/ look to you?

**Comment by Avamander** [comment]
It's much nicer, thank you.

**Comment by robsheldon** [comment]
Okay. I'll finish testing and then commit this. Thanks for the bug report and the help in resolving it.

**Comment by robsheldon** [comment]
Fixed for 0.1.0.
