### ISSUE TITLE
Publish on npm/bower?

### ISSUE THREAD

**Issue by akatechis** [robsheldon/sscaffold-css#5]
Please consider publishing on npm (maybe bower as well?) so we can manage versions using standard tools.

**Comment by cjpatoilo** [comment]
@robsheldon I can help you with that. 

To publish a scoped package with public visibility, use `npm publish --access public`.

1. On the command line, navigate to the root directory of your **package**. cd /path/to/**package**.
1. To publish your scoped public **package** to the **npm** registry, run: `npm publish --access public`.

https://zellwk.com/blog/publish-to-npm/

**Comment by robsheldon** [comment]
I've been dragging my feet on publishing it just yet because there are still a handful of important changes right around the corner -- namely some typography stuff that I didn't get right the first time.

Once that's fixed, and now that @cjpatoilo has contributed a package.json, I'll get it up on npm and bower for you folks.

**Comment by robsheldon** [comment]
It's now available on npm. I'm skipping bower since it looks like they're trying to deprecate themselves.

**Comment by robsheldon** [comment]
@cjpatoilo oh man, I just discovered you're the creator of milligram.

a. mad respect, I've used milligram a lot and love it.

b. extra thank you for being so cool and helping me out.

**Comment by cjpatoilo** [comment]
@robsheldon You're welcome! When I will have available time I will help you more. 💪

**Comment by SampsonCrowley** [comment]
@cjpatoilo is milligram still being maintained? https://github.com/milligram/milligram/issues/239#issuecomment-574952594
