### ISSUE TITLE
Consideration for System-UI font stack vs. reliance on Google Montserrat

### ISSUE THREAD

**Issue by badcat** [robsheldon/sscaffold-css#7]
Thoughts on using System UI font stack instead of an extra HTTP request (and probable privacy tracking?) when using the Google Montserrat font?  I used this with method 2 as a guide..
https://css-tricks.com/snippets/css/system-font-stack/

I did this along with a revised validated demo.html page here:
https://github.com/badcat/sscaffold-css

**Comment by jedahan** [comment]
Even distributing Montserrat locally would be a step forward for performance and privacy.

**Comment by robsheldon** [comment]
The system-ui stack trick is cool. However, there are a lot of developers that want a more consistent look than afforded by relying only on local system fonts.

sscaffold already uses font stacks to try to use common system fonts that approximate Montserrat (and now Open Sans). There's no `@import` in sscaffold for any Google web fonts, so if someone is concerned about the performance or privacy issues inherent with using Google web fonts (as I am too), then they only need to not add the external GWF links in their html. sscaffold should then fall back to a sensible alternative local font.
